require: rubocop-rspec

Documentation:
  Enabled: false

# Oops ¯\_(ツ)_/¯
Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
  - 'Rakefile'
  - 'spec/**/*.rb'
  - '*.gemspec'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/ClassLength:
  Enabled: False

Metrics/AbcSize:
  Enabled: False

RSpec/AnyInstance:
  Enabled: False

RSpec/MessageChain:
  Enabled: False

RSpec/VerifiedDoubles:
  Enabled: False
